parameters = filegroup(
	name = "parameters",
	srcs = ["parameters"],
)
shaders = filegroup(
	name = "shaders",
	srcs = ["@assets//shaders/asteroidVertexBlendShader.asl"],
)
textures = filegroup(
	name = "textures",
	srcs = [],
)
all_deps = filegroup(
	name = "all_deps",
	srcs = [":parameters",
":shaders",
":textures"],
)